In [1]:
import numpy as np

In [2]:
np.__doc__

'\nNumPy\n=====\n\nProvides\n  1. An array object of arbitrary homogeneous items\n  2. Fast mathematical operations over arrays\n  3. Linear Algebra, Fourier Transforms, Random Number Generation\n\nHow to use the documentation\n----------------------------\nDocumentation is available in two forms: docstrings provided\nwith the code, and a loose standing reference guide, available from\n`the NumPy homepage <https://numpy.org>`_.\n\nWe recommend exploring the docstrings using\n`IPython <https://ipython.org>`_, an advanced Python shell with\nTAB-completion and introspection capabilities.  See below for further\ninstructions.\n\nThe docstring examples assume that `numpy` has been imported as ``np``::\n\n  >>> import numpy as np\n\nCode snippets are indicated by three greater-than signs::\n\n  >>> x = 42\n  >>> x = x + 1\n\nUse the built-in ``help`` function to view a function\'s docstring::\n\n  >>> help(np.sort)\n  ... # doctest: +SKIP\n\nFor some objects, ``np.info(obj)`` may provide add

In [3]:
print(np.__doc__)


NumPy
=====

Provides
  1. An array object of arbitrary homogeneous items
  2. Fast mathematical operations over arrays
  3. Linear Algebra, Fourier Transforms, Random Number Generation

How to use the documentation
----------------------------
Documentation is available in two forms: docstrings provided
with the code, and a loose standing reference guide, available from
`the NumPy homepage <https://numpy.org>`_.

We recommend exploring the docstrings using
`IPython <https://ipython.org>`_, an advanced Python shell with
TAB-completion and introspection capabilities.  See below for further
instructions.

The docstring examples assume that `numpy` has been imported as ``np``::

  >>> import numpy as np

Code snippets are indicated by three greater-than signs::

  >>> x = 42
  >>> x = x + 1

Use the built-in ``help`` function to view a function's docstring::

  >>> help(np.sort)
  ... # doctest: +SKIP

For some objects, ``np.info(obj)`` may provide additional help.  This is
particularly 

In [5]:
#  An array object of arbitrary homogeneous items

o_lista = [ 1, 3, 4, 52, 32]
array = np.array(o_lista)   
array

array([ 1,  3,  4, 52, 32])

# Toate date sunt de acelasi tip - le forteaza

In [12]:
o_lista = [ 1, 3, 4, 52, 32]
array = np.array(o_lista)   
array, array.dtype

(array([ 1,  3,  4, 52, 32]), dtype('int64'))

In [10]:
o_lista = [ 1, 3, 4, 52, 32, 32.3]
array = np.array(o_lista)   
array, array.dtype

(array([ 1. ,  3. ,  4. , 52. , 32. , 32.3]), dtype('float64'))

In [11]:
o_lista = [ 1, 3, 4, 52, 32, 32.3, "hello"]
array = np.array(o_lista)   
array, array.dtype

(array(['1', '3', '4', '52', '32', '32.3', 'hello'], dtype='<U32'),
 dtype('<U32'))

In [9]:
o_lista = [ 1, 3, 4, 52, 32, 32.3, "hello"]
array = np.array(o_lista)   
array.dtype

dtype('<U32')

In [13]:
o_lista = [ 1, 3, 4, 52, 32, 32.3, "hello", [320,32]]
array = np.array(o_lista)   
array.dtype

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (8,) + inhomogeneous part.

In [18]:
o_lista = [ [320,32, 320], [32, 43, 32]]
array = np.array(o_lista)   
array, array.dtype, array.shape

(array([[320,  32, 320],
        [ 32,  43,  32]]),
 dtype('int64'),
 (2, 3))

In [20]:
o_lista = [ 1, 3, 4, 52, 32]
array = np.array(o_lista, dtype=np.int8)
array, array.dtype 

(array([ 1,  3,  4, 52, 32], dtype=int8), dtype('int8'))

## Reprezentarea numerelor in binar

In [21]:
for i in range(10):
    print(f"bin({i})={bin(i)}")


bin(0)=0b0
bin(1)=0b1
bin(2)=0b10
bin(3)=0b11
bin(4)=0b100
bin(5)=0b101
bin(6)=0b110
bin(7)=0b111
bin(8)=0b1000
bin(9)=0b1001


In [23]:
bin(2 ** 6)

'0b1000000'

In [24]:
bin(2 ** 8)

'0b100000000'

In [25]:
bin(2 ** 8 - 1) 

'0b11111111'

In [26]:
2 ** 8

256

# Maximul de reprezentare pe 0..8 bits este 255 (doar pe pozitiv)

In [28]:
o_lista = [ 1, 3, 4, 52, 32, 255]
array = np.array(o_lista, dtype=np.uint8)
array, array.dtype 

(array([  1,   3,   4,  52,  32, 255], dtype=uint8), dtype('uint8'))

In [29]:
o_lista = [ 1, 3, 4, 52, 32, 256]
array = np.array(o_lista, dtype=np.uint8)
array, array.dtype 

OverflowError: Python integer 256 out of bounds for uint8

# Maximul de reprezentare pe 0..8 bits este 255. (-128 pana la 127)     

In [31]:
o_lista = [ 1, 3, 4, 52, 32, 127]
array = np.array(o_lista, dtype=np.int8)
array, array.dtype 


(array([  1,   3,   4,  52,  32, 127], dtype=int8), dtype('int8'))

In [33]:
o_lista = [ 1, 3, 4, 52, 32, -128]
array = np.array(o_lista, dtype=np.int8)
array, array.dtype 

(array([   1,    3,    4,   52,   32, -128], dtype=int8), dtype('int8'))

In [34]:
o_lista = [ 1, 3, 4, 52, 32, -129]
array = np.array(o_lista, dtype=np.int8)
array, array.dtype 

OverflowError: Python integer -129 out of bounds for int8

# Numpy - operatii matematice rapide 

In [35]:
a = np.array([2, 3, 9])
a

array([2, 3, 9])

In [36]:
a + 100

array([102, 103, 109])

In [37]:
[2, 3, 9] + 100

TypeError: can only concatenate list (not "int") to list

# Concatenare a 2 lista

In [38]:
[2, 3, 9] + [100]

[2, 3, 9, 100]

# Calcul clasic

In [39]:
o_lista = [2, 3, 9]
for i in range(len(o_lista)):
    o_lista[i] = o_lista[i] + 100

o_lista


[102, 103, 109]

# List comprehention

In [41]:
o_lista = [2, 3, 9]
o_noua_lista = [ o_lista[i] + 100  for i in range(len(o_lista))  ]
o_noua_lista

[102, 103, 109]

# Programare functionala

In [40]:
def aduna_100(x):
    return x + 100


o_lista = [2, 3, 9]
print(list(map(aduna_100, o_lista)))


[102, 103, 109]


# Numpy - operatii matematice rapide 

In [42]:
array = np.array([321, 412, 10, 32])
array 

array([321, 412,  10,  32])

In [43]:
array / 23 

array([13.95652174, 17.91304348,  0.43478261,  1.39130435])

In [44]:
array + array

array([642, 824,  20,  64])

In [45]:
array - array

array([0, 0, 0, 0])

## Generare de numere random

In [46]:
np.random.random(5)

array([0.57046346, 0.55677752, 0.97265196, 0.15829468, 0.60583457])

In [56]:
np.random.randint(0, 10)

9

In [57]:
np.random.randint(0, 10, 5)

array([2, 4, 0, 5, 2])

In [58]:
np.random.randint(0, 10, 25)

array([6, 2, 1, 0, 6, 7, 1, 3, 8, 7, 6, 0, 2, 8, 1, 6, 6, 0, 8, 6, 6, 3,
       8, 1, 6])

In [59]:
array = np.random.randint(0, 10, 25)
array

array([1, 2, 2, 1, 5, 7, 8, 9, 1, 0, 4, 9, 6, 8, 3, 9, 4, 0, 7, 8, 1, 8,
       6, 8, 4])

In [60]:
array > 5

array([False, False, False, False, False,  True,  True,  True, False,
       False, False,  True,  True,  True, False,  True, False, False,
        True,  True, False,  True,  True,  True, False])

In [61]:
array % 2 == 0

array([False,  True,  True, False, False, False,  True, False, False,
        True,  True, False,  True,  True, False, False,  True,  True,
       False,  True, False,  True,  True,  True,  True])

# Filtrarea elementelor

In [62]:
array [array > 5]

array([7, 8, 9, 9, 6, 8, 9, 7, 8, 8, 6, 8])

In [63]:
array[array % 2 == 0]

array([2, 2, 8, 0, 4, 6, 8, 4, 0, 8, 8, 6, 8, 4])

## 