In [164]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OrdinalEncoder, StandardScaler
from sklearn.compose import ColumnTransformer


In [165]:
date = {
    "Alina": [60, 165, True],
    "Bogdan": [72, 183, False],
    "Ciprian": [69, 178, False],
    "Diana": [55, 152, True],
    "Elena": [58, 168, True],
    "Andrei": [80, 185, False],
    "Mihai": [75, 177, False],
    "Irina": [62, 170, True],
    "Florin": [90, 190, False],
    "Maria": [53, 160, True],
    "Vlad": [70, 175, False],
    "Ioana": [50, 155, True],
    "Radu": [68, 172, False],
    "Ana": [59, 162, True],
    "George": [85, 182, False],
    "Larisa": [61, 167, True],
    "Stefan": [78, 180, False],
    "Bianca": [56, 158, True],
    "Paul": [74, 176, False],
    "Oana": [54, 163, True],
    "Cosmin": [82, 188, False],
    "Teodora": [57, 159, True],
    "Ionut": [76, 181, False],
    "Gabriela": [60, 164, True]
}

In [166]:
pd.DataFrame(date)

Alina Bogdan Ciprian Diana Elena Andrei  Mihai Irina Florin Maria  ...  \
0    60     72      69    55    58     80     75    62     90    53  ...   
1   165    183     178   152   168    185    177   170    190   160  ...   
2  True  False   False  True  True  False  False  True  False  True  ...   

  George Larisa Stefan Bianca   Paul  Oana Cosmin Teodora  Ionut Gabriela  
0     85     61     78     56     74    54     82      57     76       60  
1    182    167    180    158    176   163    188     159    181      164  
2  False   True  False   True  False  True  False    True  False     True  

[3 rows x 24 columns]

In [167]:
df = pd.DataFrame(date.values(), index=date.keys(), columns=("Varsta", "Inaltime", "Voce_Subtire"))
df

Varsta  Inaltime  Voce_Subtire
Alina         60       165          True
Bogdan        72       183         False
Ciprian       69       178         False
Diana         55       152          True
Elena         58       168          True
Andrei        80       185         False
Mihai         75       177         False
Irina         62       170          True
Florin        90       190         False
Maria         53       160          True
Vlad          70       175         False
Ioana         50       155          True
Radu          68       172         False
Ana           59       162          True
George        85       182         False
Larisa        61       167          True
Stefan        78       180         False
Bianca        56       158          True
Paul          74       176         False
Oana          54       163          True
Cosmin        82       188         False
Teodora       57       159          True
Ionut         76       181         False
Gabriela      60       164          True

In [168]:
standard_scaler = StandardScaler()
standard_scaler

StandardScaler()

In [169]:
standard_scaler.fit_transform(df)

array([[-0.61915453, -0.58660023,  1.        ],
       [ 0.46814123,  1.10280844, -1.        ],
       [ 0.19631729,  0.63352825, -1.        ],
       [-1.07219444, -1.80672872,  1.        ],
       [-0.8003705 , -0.30503212,  1.        ],
       [ 1.19300508,  1.29052052, -1.        ],
       [ 0.73996518,  0.53967222, -1.        ],
       [-0.43793857, -0.11732005,  1.        ],
       [ 2.09908489,  1.7598007 , -1.        ],
       [-1.2534104 , -1.05588042,  1.        ],
       [ 0.28692527,  0.35196014, -1.        ],
       [-1.52523434, -1.52516061,  1.        ],
       [ 0.10570931,  0.07039203, -1.        ],
       [-0.70976252, -0.86816835,  1.        ],
       [ 1.64604498,  1.0089524 , -1.        ],
       [-0.52854655, -0.39888816,  1.        ],
       [ 1.01178912,  0.82124033, -1.        ],
       [-0.98158646, -1.2435925 ,  1.        ],
       [ 0.64935719,  0.44581618, -1.        ],
       [-1.16280242, -0.77431231,  1.        ],
       [ 1.37422104,  1.57208863, -1.   

In [170]:
numeric_transformer = Pipeline(steps=[
    ("scaler", StandardScaler())
])
numeric_transformer

Pipeline(steps=[('scaler', StandardScaler())])

In [171]:
categorical_transformer = Pipeline(steps=[
    ("encoder", OrdinalEncoder())
])
categorical_transformer

Pipeline(steps=[('encoder', OrdinalEncoder())])

In [172]:
df.keys()

Index(['Varsta', 'Inaltime', 'Voce_Subtire'], dtype='object')

In [173]:
numeric_features = ["Varsta", "Inaltime"]
categorical_features = ["Voce_Subtire"]

In [174]:
preprocessor = ColumnTransformer(
    transformers=[ 
        ("num", numeric_transformer, numeric_features),
        ("cat", categorical_transformer, categorical_features)
    ]
)
preprocessor

ColumnTransformer(transformers=[('num',
                                 Pipeline(steps=[('scaler', StandardScaler())]),
                                 ['Varsta', 'Inaltime']),
                                ('cat',
                                 Pipeline(steps=[('encoder',
                                                  OrdinalEncoder())]),
                                 ['Voce_Subtire'])])

In [175]:
# x_train = pd.DataFrame( preprocessor.fit_transform(df), columns=df.keys())
# x_train.head(2)

In [176]:
from sklearn.ensemble import RandomForestClassifier

In [177]:
model_pipeline = Pipeline(
    steps=[
        ("preprocessor", preprocessor),
        ("model",  RandomForestClassifier())
    
    ]
)

In [178]:
df["Gen"] =  LabelEncoder().fit_transform(df["Voce_Subtire"])
x_train = df.drop("Gen", axis=1)
y_train =df[["Gen"]]


In [179]:
model_pipeline.fit(x_train, y_train)

/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/sklearn/base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)


Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('num',
                                                  Pipeline(steps=[('scaler',
                                                                   StandardScaler())]),
                                                  ['Varsta', 'Inaltime']),
                                                 ('cat',
                                                  Pipeline(steps=[('encoder',
                                                                   OrdinalEncoder())]),
                                                  ['Voce_Subtire'])])),
                ('model', RandomForestClassifier())])

In [180]:
x_train.head(2)

Varsta  Inaltime  Voce_Subtire
Alina       60       165          True
Bogdan      72       183         False

In [181]:
x_train.head(2).to_numpy()

array([[60, 165, True],
       [72, 183, False]], dtype=object)

In [182]:
x_train.keys()

Index(['Varsta', 'Inaltime', 'Voce_Subtire'], dtype='object')

In [186]:
x_test = pd.DataFrame([[50, 168, True], [45, 170, False]], columns=x_train.keys())
x_test

Varsta  Inaltime  Voce_Subtire
0      50       168          True
1      45       170         False

In [187]:
model_pipeline.predict(x_test)

array([1, 0])